name: capstone_proj
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  flutter_native_splash: ^2.3.0
  dotted_border: ^2.1.0
  google_mlkit_text_recognition: ^0.14.0
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  highlight_text: ^1.7.0
  provider: ^6.1.2
  feedback: ^3.0.1
  flutter_email_sender: ^6.0.3
  google_generative_ai: ^0.4.4
  path_provider: ^2.0.20
  file_picker: ^8.1.7
  http: ^1.2.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^11.0.0
  flutter_secure_storage: ^9.2.4
  signalr_netcore: ^1.4.0
  flutter_plugin_android_lifecycle: ^2.0.24
  shimmer: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#4a4a4a"
  image: images/Logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Anta
      fonts:
        - asset: fonts/Anta-Regular.ttf